# PostgreSQL. Versions 8.2 and up are supported.
#
# Install the pg driver:
# gem install pg
#
# Configure Using Gemfile
# gem 'pg'
#
development:
  adapter: postgresql
  encoding: unicode
  reconnect: false
  database: invoicing_system
  pool: 5
  host: localhost
  username: postgres
  password: 'postgres'

test:
  adapter: postgresql
  encoding: unicode
  database: my_app_test
  pool: 5
  username: my_app
  password:

production:
  adapter: postgresql
  encoding: unicode
  host: localhost
  database: invoicing_system
  pool: 5
  username: postgres
  password: 'postgres'

